spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to EazyBank cards related QA APIs "
  contactDetails:
    name: "Cherryl Pankaj - QA Lead"
    email: "{cipher}e6af5b2357dc379866539daf011a13ecdbc9121648a9a5370b1d066a6aeb26c74c3081b855c96eb827a8b4d2146877a8"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267
